name = "basalt"
version = "0.1.0"
defaultTargets = ["Basalt", "Examples"]

[[lean_lib]]
name = "Basalt"

[[lean_lib]]
name = "Examples"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.29.0"
