name = "basalt"
version = "0.1.0"
defaultTargets = ["basalt", "bdt_experiments"]

[[lean_lib]]
name = "Basalt"

[[lean_exe]]
name = "basalt"
root = "Main"

[[lean_exe]]
name = "bdt_experiments"
root = "Basalt.Experiments.BDT.Main"

[[require]]
name = "mathlib"
scope = "leanprover-community"
