/-
Copyright (c) 2026 Harrison Goldstein & Ernest Ng. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: Harrison Goldstein & Ernest Ng
-/
import Basalt
import Basalt.PlausibleGen
import BasaltExamples.STLC.Syntax
import BasaltExamples.STLC.GenType

open RandomChoice SPMF List

/-!
# Generating Well-Typed STLC Terms

The `genTerm` generator produces a well-typed term at a given type in a given context, along with
the helper generators it is built from (`genBool`, `genZero`, `varsWithType`) and soundness and
completeness proofs.
-/

def Bool.arbitrary [Gen G] : G Bool :=
  pick (fun _ => pure true) (fun _ => pure false)

/-- Generates a term that's a Boolean literal -/
def genBool [Gen G] : G Term :=
  Term.Bool <$> Bool.arbitrary

/-- Any term generated by `genBool` is of the form `.Bool b` for some `b` -/
theorem genBool_inversion :
    e ∈ SPMF.support genBool → ∃ b, e = .Bool b := by
  intro h
  simp [genBool] at h
  rcases h with h | h
  . obtain ⟨_, heq⟩ := h
    subst heq
    exists false
  . obtain ⟨_, heq⟩ := h
    subst heq
    exists true

/-- Bools produced by `genBool` are always well-typed -/
theorem genBool_sound :
    b ∈ SPMF.support genBool → Typing Γ b .Bool := by
  intro h
  simp [genBool] at h
  cases h with
  | inl h =>
    obtain ⟨hmem, heq⟩ := h
    subst heq
    constructor
  | inr h =>
    obtain ⟨hmem, heq⟩ := h
    subst heq
    constructor

/-- Finds all variables in `Γ` that have type `τ` -/
def varsWithType (Γ : Ctx) (τ : Ty) : List Term :=
  Γ.zipIdx.filterMap (fun (τ', i) => if τ' == τ then some (Term.Var i) else none)

/-- Generates a term with size 0 -/
def genZero [Gen G] (Γ : Ctx) (τ : Ty) : G Term :=
  match τ with
  | .Bool => genBool
  | .Fun τ1 τ2 => do
    let e ← genZero (τ1 :: Γ) τ2
    return .Abs τ1 e

/-- Any term produced by `genZero` is well-typed -/
theorem genZero_sound :
    e ∈ SPMF.support (genZero Γ τ) → Typing Γ e τ := by
  induction τ generalizing Γ e with
  | Bool =>
    intro h
    simp [genZero] at h
    apply genBool_sound at h
    assumption
  | Fun τ1 τ2 IH1 IH2 =>
    intro h
    simp [genZero] at h
    obtain ⟨body, hbody, heq⟩ := h
    subst heq
    constructor
    apply IH2
    assumption

/-- `genZero` produces either a well-typed `Bool` or an `Abs` -/
theorem genZero_inversion :
    e ∈ SPMF.support (genZero Γ τ) → (∃ b, e = .Bool b ∧ Typing Γ e .Bool) ∨ (∃ e' τ1 τ2, e = .Abs τ1 e' ∧ Typing Γ e (.Fun τ1 τ2)) := by
  intro h
  unfold genZero at h
  cases τ with
  | Bool =>
    dsimp at h
    have htyping : Typing Γ e .Bool := by
      apply genBool_sound
      assumption
    left
    have hb : ∃ b, e = .Bool b := by
      apply genBool_inversion
      assumption
    obtain ⟨b', heq⟩ := hb
    exists b'
  | Fun τ1 τ2 =>
    simp at h
    obtain ⟨e', ⟨hmem, heq⟩⟩ := h
    right
    exists e', τ1, τ2
    constructor
    . assumption
    . subst heq
      constructor
      apply genZero_sound at hmem
      assumption

/-- All terms in the list produced by `varsWithType` are sound -/
theorem varsWithType_sound :
    e ∈ varsWithType Γ τ → Typing Γ e τ := by
  intro h
  simp [varsWithType] at h
  obtain ⟨i, hmem, rfl⟩ := h
  apply Typing.TVar
  rw [mk_mem_zipIdx_iff_getElem?] at hmem
  apply getElem?_lookup
  assumption

/-- If `lookup Γ x τ` holds, then `Var x` is contained in the output of `varsWithType Γ τ` -/
theorem varsWithType_complete :
    lookup Γ x τ → Term.Var x ∈ varsWithType Γ τ := by
  intro h
  simp only [varsWithType, List.mem_filterMap]
  refine ⟨(τ, x), ?_, by simp⟩
  rw [mk_mem_zipIdx_iff_getElem?]
  exact lookup_getElem? h


/-- Generates a well-typed term at type `τ` in context `Γ`. -/
def genTerm [Gen G] (Γ : Ctx) (τ : Ty) : G Term :=
  let vars := varsWithType Γ τ
  if hne : vars ≠ [] then
    oneOf [
      fun _ => genZero Γ τ,
      fun _ => elements vars hne,
      fun _ => do
        let argTy ← genType
        let e1 ← genTerm Γ (.Fun argTy τ)
        let e2 ← genTerm Γ argTy
        return .App e1 e2,
      fun _ =>
        match τ with
        | .Bool => genBool
        | .Fun τ1 τ2 => do
          let e ← genTerm (τ1 :: Γ) τ2
          return .Abs τ1 e
    ] (by apply cons_ne_nil)
  else
    oneOf [
      fun _ => genZero Γ τ,
      fun _ => do
        let argTy ← genType
        let e1 ← genTerm Γ (.Fun argTy τ)
        let e2 ← genTerm Γ argTy
        return .App e1 e2,
      fun _ =>
        match τ with
        | .Bool => genBool
        | .Fun τ1 τ2 => do
          let e ← genTerm (τ1 :: Γ) τ2
          return .Abs τ1 e
    ] (by apply cons_ne_nil)
partial_fixpoint

/-- All well-typed terms are in `genTerm`'s suport -/
theorem genTerm_complete :
    Typing Γ e τ → e ∈ SPMF.support (genTerm Γ τ) := by
  intro h
  induction h with
  | TBool Γ b =>
    rw [genTerm]
    support_simp [mem_support_oneOf_iff]
    by_cases hne : varsWithType Γ Ty.Bool ≠ []
    · -- varsWithType Γ Ty.Bool ≠ []
      left
      refine ⟨hne, fun _ => genBool, ?_⟩
      simp
      cases b <;> simp [genBool, Bool.arbitrary]
    ·-- varsWithType Γ Ty.Bool = []
      right
      refine ⟨hne, fun _ => genBool, ?_⟩
      simp
      cases b <;> simp [genBool, Bool.arbitrary]
  | TVar Γ x τ hlookup =>
    unfold genTerm
    support_simp [mem_support_oneOf_iff]
    left
    have hmem : .Var x ∈ varsWithType Γ τ := by
      apply varsWithType_complete
      assumption
    have hne : varsWithType Γ τ ≠ [] := by
      apply List.ne_nil_of_mem
      assumption
    exists hne, (fun _ => elements (varsWithType Γ τ) hne)
    simp
    assumption
  | TAbs Γ body τ1 τ2 hbody IH =>
    rw [genTerm]
    support_simp [mem_support_oneOf_iff]
    by_cases hne : varsWithType Γ (.Fun τ1 τ2) ≠ []
    . left
      exists hne, (fun _ => do
        let e ← genTerm (τ1 :: Γ) τ2
        return (.Abs τ1 e))
      simp
      assumption
    . right
      exists hne, (fun _ => do
        let e ← genTerm (τ1 :: Γ) τ2
        return (.Abs τ1 e))
      simp
      assumption
  | TApp Γ e1 e2 τ1 τ2 h2 h1 IH2 IH1 =>
    unfold genTerm
    support_simp [mem_support_oneOf_iff]
    by_cases hne : varsWithType Γ τ2 ≠ []
    . left
      exists hne, (fun _ => do
        let argTy ← genType
        let e1 ← genTerm Γ (.Fun argTy τ2)
        let e2 ← genTerm Γ argTy
        return (.App e1 e2))
      simp
      exists τ1
      constructor
      . apply genType_support
      . constructor <;> assumption
    . right
      exists hne, (fun _ => do
        let argTy ← genType
        let e1 ← genTerm Γ (.Fun argTy τ2)
        let e2 ← genTerm Γ argTy
        return (.App e1 e2))
      simp
      exists τ1
      constructor
      . apply genType_support
      . constructor <;> assumption

/-- All terms generated by `genTerm Γ τ` are well-typed -/
theorem genTerm_sound :
    e ∈ SPMF.support (genTerm Γ τ) → Typing Γ e τ := by
  induction e generalizing Γ τ with
  | Bool b =>
    intro h
    unfold genTerm at h
    cases τ with
    | Bool => exact Typing.TBool Γ b
    | Fun τ1 τ2 =>
      -- `Bool b` cannot be produced at a function type, contradiction
      exfalso
      support_simp [genZero] at h
      simp [varsWithType] at h
  | Var n =>
    intro h
    unfold genTerm at h
    -- A `Var` can only come from the `varsWithType` branch; the `genZero`,
    -- `App`, and `genBool`/`Abs` branches are all constructor clashes.
    cases τ with
    | Bool =>
      support_simp [genZero, genBool] at h
      simp at h
      obtain ⟨_, hv⟩ := h
      apply varsWithType_sound; assumption
    | Fun τ1 τ2 =>
      support_simp [genZero] at h
      simp at h
      obtain ⟨_, hv⟩ := h
      apply varsWithType_sound; assumption
  | Abs τ' e1 IH =>
    intro h
    unfold genTerm at h
    cases τ with
    | Bool =>
      -- Can't have an `Abs` at type `Bool`, a contradiction
      support_simp [genZero, genBool] at h
      simp at h
      obtain ⟨_, hv⟩ := h
      cases varsWithType_sound hv
    | Fun τ1 τ2 =>
      -- An `Abs τ' e1` with type `Fun τ1 τ2` comes from either `genZero` or the
      -- recursive `Abs` branch
      support_simp [genZero] at h
      simp [varsWithType] at h
      rcases h with ⟨_, hz | hg⟩ | ⟨_, hz | hg⟩
      · obtain ⟨a, ha, rfl, rfl⟩ := hz
        apply Typing.TAbs; apply genZero_sound; assumption
      · obtain ⟨a, ha, rfl, rfl⟩ := hg
        apply Typing.TAbs; apply IH; assumption
      · obtain ⟨a, ha, rfl, rfl⟩ := hz
        apply Typing.TAbs; apply genZero_sound; assumption
      · obtain ⟨a, ha, rfl, rfl⟩ := hg
        apply Typing.TAbs; apply IH; assumption
  | App e1 e2 IH1 IH2 =>
    intro h
    unfold genTerm at h
    -- An `App` only comes from the application branch
    cases τ with
    | Bool =>
      support_simp [genZero, genBool] at h
      simp [varsWithType] at h
      rcases h with ⟨_, hf⟩ | ⟨_, hf⟩
      all_goals
        obtain ⟨argTy, _, hf, hx⟩ := hf
        apply Typing.TApp
        · apply IH2; assumption
        · apply IH1; assumption
    | Fun τ1 τ2 =>
      support_simp [genZero] at h
      simp [varsWithType] at h
      rcases h with ⟨_, hf⟩ | ⟨_, hf⟩
      all_goals
        obtain ⟨argTy, _, hf, hx⟩ := hf
        apply Typing.TApp
        · apply IH2; assumption
        · apply IH1; assumption



#guard_msgs(drop info) in
#eval (for _ in [0:3] do
  IO.println <| repr (← genTerm [] .Bool) : IO Unit)

#guard_msgs(drop info) in
#eval (for _ in [0:3] do
  IO.println <| repr (← genTerm [] (.Fun .Bool .Bool)) : IO Unit)
