/-
Copyright (c) 2026 Harrison Goldstein & Ernest Ng. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: Harrison Goldstein & Ernest Ng
-/
import Basalt.Gen
import Basalt.RandomChoice

/-!
# Generator Combinators

Derived combinators (`chooseNat`, `elements`, `oneOf`, `frequency`, `listOf`, …) built on
`RandomChoice.choose`.
-/

open Lean.Order

open List

section side_condition_tactic

/-- This tactic discharges common side conditions for `chooseNat`, `elements`, and `frequency`. -/
syntax "gen_side_condition" : tactic

macro_rules
  | `(tactic| gen_side_condition) =>
    `(tactic| first
        | (simp; done)
        | (simp_all only [decide_eq_true_eq]; done)
        | (simp_all; done))

end side_condition_tactic

section combinators

/-- Choose a plain `Nat` uniformly from `[lo, hi]` (inclusive). Prefer this over raw `choose` in
generators: it hides `choose`'s `ULift` subtype from bodies and proofs. -/
def chooseNat [Gen G] (lo hi : Nat) (h : lo ≤ hi := by gen_side_condition) : G Nat :=
  (·.down.val) <$> RandomChoice.choose lo hi h

/-- Same as `chooseNat` but for signed `Int`s.  -/
def chooseInt [Gen G] (lo hi : Int) (_h : lo ≤ hi := by gen_side_condition) : G Int := do
  let k ← chooseNat 0 (hi - lo).toNat (Nat.zero_le _)
  return lo + (k : Int)

/-- Generates an element of the list `xs` at random.  This combinator takes as input a proof that
`xs` is non-empty, discharged by `gen_side_condition` when omitted. -/
def elements [Gen G] (xs : List α) (hne : xs ≠ [] := by gen_side_condition) : G α := do
  let ⟨i, ⟨ hge, hle ⟩⟩ ← ULift.down <$> RandomChoice.choose 0 (xs.length - 1) (by omega)
  have hlen : 0 < xs.length := by
    apply length_pos_iff.mpr
    assumption
  have hlt : i < xs.length := by omega
  return xs[i]'hlt

/-- Picks one of the generators in `gs` at random.  This combinator takes as input a proof that `gs`
is non-empty, discharged by `gen_side_condition` when omitted. -/
def oneOf {G : Type u → Type v} {α : Type u} [Gen G] (gs : List (Unit → G α))
    (hne : gs ≠ [] := by gen_side_condition) : G α := do
  let i ← RandomChoice.choose 0 (gs.length - 1) (Nat.zero_le _)
  (gs[i.down.val]'(by
    have := i.down.property.2
    have : 0 < gs.length := length_pos_iff.mpr hne
    omega)) ()

/-- Core of the `frequency` combinator: `frequencyAux xs n` chooses a weight & a generator
`(k, gen)` from the list `xs` such that `n < k`. -/
def frequencyAux [Gen G] (xs : List (Nat × (Unit → G α))) (n : Nat)
    (h : n < List.sum (List.map Prod.fst xs)) : G α :=
  match xs with
  | [] => by contradiction
  | (k, x) :: xs =>
    if hlt : n < k then
      x ()
    else
      frequencyAux xs (n - k) (by simp only [List.map_cons, List.sum_cons] at h; omega)

/-- `frequency` picks a generator from the list `gs` according to the weights in `gs`.  This
combinators also takes an additional hypothesis that the sum of the weights in the list is non-zero
(this is discharged by `gen_side_condition` when omitted). -/
def frequency [Gen G] (gs : List (Nat × (Unit → G α)))
  (_h : 0 < List.sum (List.map Prod.fst gs) := by gen_side_condition) : G α := do
  let n ← chooseNat 0 (List.sum (List.map Prod.fst gs) - 1) (Nat.zero_le _)
  if hn : n < List.sum (List.map Prod.fst gs) then
    frequencyAux gs n hn
  else
    default

/-- Generates a length-`n` list, where each element is generated by the generator `g` -/
def vectorOf [Gen G] (n : Nat) (g : G α) : G (List α) :=
  List.foldr (fun m acc => do
    let x ← m
    let xs ← acc
    pure (x :: xs)) (pure []) (List.replicate n g)

/-- Helper lemma that unfolds one layer of recursion in `vectorOf (n + 1) g`.  This is needed for
the lemmas `support_vectorOf`, `le_mass_vectorOf`. -/
theorem vectorOf_succ [Gen G] {n : Nat} {g : G α} :
    vectorOf (n + 1) g = (do let x ← g; let xs ← vectorOf n g; pure (x :: xs)) :=
  rfl

/-- `listOfMaxLength n g` generates a list whose length is unformly distributed across `[0, n]`,
(i.e. the list may be empty and its maximum possible length is `n` inclusive). Each list element is
produced by the generator `g`. -/
def listOfMaxLength [Gen G] (n : Nat) (g : G α) : G (List α) := do
  let ⟨k, _⟩ ← ULift.down <$> RandomChoice.choose 0 n (Nat.zero_le n)
  vectorOf k g

/-- Generates a random permutation of the list `xs`, along with a proof
    that the resultant list is indeed a permutation of `xs`.

    Implementation closely mirrors `Plausible.Gen.permutationOf`. -/
def permutationOf [Gen G] : (xs : List α) → G { ys // xs ~ ys }
  | [] => pure ⟨[], Perm.nil⟩
  | x :: xs => do
    let ⟨ys, h1⟩ ← permutationOf xs
    let ⟨n, _, h3⟩ ← ULift.down <$> RandomChoice.choose 0 ys.length (Nat.zero_le _)
    return ⟨ys.insertIdx n x, (Perm.cons x h1).trans (List.perm_insertIdx x ys h3).symm⟩

end combinators

section monotonicity

/-- Define a partial order over `List α` that says `l1 ⊑ l2` when:
- `l1.length = l2.length`
- `l1[i] ⊑ l2[i]` for all list elements (here we are comparing them using the `PartialOrder` on `α`) -/
private instance List.instPartialOrderPointwise {α : Type u} [PartialOrder α] :
    PartialOrder (List α) where
  rel l1 l2 :=
    l1.length = l2.length ∧
    ∀ (i : Nat) (h1 : i < l1.length) (h2 : i < l2.length), l1[i] ⊑ l2[i]
  rel_refl := by
    intro xs
    constructor
    . rfl
    . intro i _ _
      apply PartialOrder.rel_refl
  rel_trans := by
    intro xs ys zs h12 h23
    obtain ⟨heq1, hle1⟩ := h12
    obtain ⟨heq2, hle2⟩ := h23
    constructor
    . apply Eq.trans <;> assumption
    . intro i h1 h2
      apply PartialOrder.rel_trans
      . apply hle1
        omega
      . apply hle2
  rel_antisymm := by
    intro x y hxy hyx
    obtain ⟨hlen, helem_xy⟩ := hxy
    obtain ⟨_, helem_yx⟩ := hyx
    apply List.ext_getElem hlen
    intro i hx hy
    apply PartialOrder.rel_antisymm
    . apply helem_xy
    . apply helem_yx

/-- The partial order on `Nat × α` behind `frequency`'s monotonicity: `(w1, g1) ⊑ (w2, g2)` iff
`w1 = w2 ∧ g1 ⊑ g2`. The weights must be *equal*, not `≤` — raising one branch's weight lowers every
other branch's probability, so under `w1 ≤ w2` the `frequency` combinator would not be monotone in
`⊑` on `SPMF`. -/
private instance instPartialOrderConstFst {α : Type u} [PartialOrder α] : PartialOrder (Nat × α) where
  rel p q := p.1 = q.1 ∧ p.2 ⊑ q.2
  rel_refl := by
    intro p
    constructor
    . rfl
    . apply PartialOrder.rel_refl
  rel_trans := by
    intro p q r hpq hqr
    obtain ⟨hw1, hg1⟩ := hpq
    obtain ⟨hw2, hg2⟩ := hqr
    constructor
    . apply hw1.trans; assumption
    . apply PartialOrder.rel_trans <;> assumption
  rel_antisymm := by
    intro p q hpq hqp
    obtain ⟨hw, hg⟩ := hpq
    obtain ⟨_, hg'⟩ := hqp
    apply Prod.ext
    . assumption
    . apply PartialOrder.rel_antisymm <;> assumption

@[partial_fixpoint_monotone]
theorem List.monotone_cons
    {α : Type u} {γ : Sort w} [PartialOrder α] [PartialOrder γ]
    (f : γ → α) (fs : γ → List α) (hf : monotone f) (hfs : monotone fs) :
    monotone (fun x => f x :: fs x) := by
  intro x y hxy
  have hle : fs x ⊑ fs y := hfs x y hxy
  have heq : (fs x).length = (fs y).length := hle.1
  dsimp
  constructor
  . simpa using heq
  . intro i h1 h2
    cases i with
    | zero =>
      apply hf
      assumption
    | succ i' =>
      dsimp
      have all_elts_le := (hfs x y hxy).2
      apply all_elts_le

/-- Monotonicity of `frequencyAux`: if `l1 ⊑ l2` and the same random weight `n` is in less than
each list's sum of weights (`h1`, `h2`), then `frequencyAux l1 n h1 ⊑ frequencyAux l2 n h2` -/
private theorem frequencyAux_le [Gen G] {l1 l2 : List (Nat × (Unit → G α))} {n : Nat}
    (hle : l1 ⊑ l2)
    (h1 : n < List.sum (List.map Prod.fst l1))
    (h2 : n < List.sum (List.map Prod.fst l2)) :
    frequencyAux l1 n h1 ⊑ frequencyAux l2 n h2 := by
  induction l1 generalizing n l2 with
  | nil => contradiction
  | cons hd xs IH =>
    obtain ⟨k, g⟩ := hd
    obtain ⟨hlen_eq, hrel⟩ := hle
    cases l2 with
    | nil => contradiction
    | cons hd' ys =>
      obtain ⟨k', g'⟩ := hd'
      have hzero := hrel 0 (by simp) (by simp)
      obtain ⟨hweight, helt⟩ := hzero
      simp [List.getElem_cons_zero] at hweight helt
      subst hweight
      unfold frequencyAux
      split
      . apply helt
      . have htail : xs ⊑ ys := by
          constructor
          . injection hlen_eq
          . intro i hi1 hi2
            specialize hrel (i + 1)
            dsimp at hrel
            apply hrel <;> omega
        apply IH
        assumption

/-- If two lists `l1, l2 : List (Nat × α)` satisfy `l1 ⊑ l2`, then the sum of their weights must be
equal -/
private theorem sumOfWeights_le {α : Type u} [PartialOrder α] {l1 l2 : List (Nat × α)}
      (hle : l1 ⊑ l2) :
      List.sum (List.map Prod.fst l1) = List.sum (List.map Prod.fst l2) := by
  obtain ⟨hlen, hrel⟩ := hle
  congr 1
  apply List.ext_getElem
  . repeat rw [List.length_map]
    assumption
  . intro i h1 h2
    rw [List.length_map] at h1 h2
    specialize hrel i h1 h2
    obtain ⟨hlen, hle⟩ := hrel
    simp only [getElem_map]
    assumption

/-- Two draws whose (equal) upper bounds are written differently agree: the bound appears in the
type of the drawn value, so it can only be transported where it is a variable. -/
private theorem bind_choose_congr {G : Type u → Type v} [Gen G] {β : Type u} {n n' : Nat}
    (hn : n = n') (f : (i : Nat) → i ≤ n → G β) :
    (RandomChoice.choose 0 n (Nat.zero_le _) >>= fun i => f i.down.val i.down.property.2)
      = (RandomChoice.choose 0 n' (Nat.zero_le _) >>= fun i =>
          f i.down.val (by have := i.down.property.2; omega)) := by
  subst hn
  rfl

/-- Monotonicity of `oneOf`: if lists `l1, l2` are both non-empty (`h1, h2`) and `l1 ⊑ l2`,
    then `oneOf l1 h1 ⊑ oneOf l2 h2` -/
private theorem oneOf_le [Gen G] {l1 l2 : List (Unit → G α)} (h : l1 ⊑ l2) (h1 : l1 ≠ []) (h2 : l2 ≠ []) :
    oneOf l1 h1 ⊑ oneOf l2 h2 := by
  obtain ⟨hlen_eq, hle⟩ := h
  have h1len : 0 < l1.length := List.length_pos_iff.mpr h1
  have h2len : 0 < l2.length := List.length_pos_iff.mpr h2
  rw [show oneOf l1 h1
        = RandomChoice.choose 0 (l2.length - 1) (Nat.zero_le _) >>= fun i =>
            (l1[i.down.val]'(by have := i.down.property.2; omega)) ()
      from bind_choose_congr (by omega) (fun i hi => (l1[i]'(by omega)) ())]
  simp only [oneOf]
  apply MonoBind.bind_mono_right
  intro i
  apply hle

@[partial_fixpoint_monotone]
theorem monotone_oneOf [Gen G] {γ : Sort w} [PartialOrder γ]
    (gs : γ → List (Unit → G α)) (hne : ∀ x, gs x ≠ []) (hmono : monotone gs) :
    monotone (fun x => oneOf (gs x) (hne x)) := by
  intro x y hxy
  unfold monotone at hmono
  apply oneOf_le
  apply hmono
  assumption

/-- A uniform binary choice. -/
@[deprecated "use `oneOf [x, y]`" (since := "2026-09-22")]
def RandomChoice.pick [Gen G] (x y : Unit → G α) : G α := oneOf [x, y]

set_option linter.deprecated false in
@[partial_fixpoint_monotone, deprecated monotone_oneOf (since := "2026-09-22")]
theorem RandomChoice.monotone_pick [Gen G] {γ : Sort w} [PartialOrder γ] {x y : γ → G α}
    (hx : monotone x) (hy : monotone y) :
    monotone fun a => RandomChoice.pick (fun () => x a) (fun () => y a) :=
  monotone_oneOf (fun a => [fun () => x a, fun () => y a]) (fun _ => by simp)
    (List.monotone_cons _ _ (monotone_of_monotone_apply _ fun _ => hx)
      (List.monotone_cons _ _ (monotone_of_monotone_apply _ fun _ => hy) (monotone_const _)))

@[partial_fixpoint_monotone]
theorem monotone_pair_snd {α : Type u} {γ : Sort w} [PartialOrder α] [PartialOrder γ]
    (w : Nat) (g : γ → α) (hg : monotone g) :
    monotone (fun x => (w, g x)) := by
  intro x y hxy
  exact ⟨rfl, hg x y hxy⟩

/-- Monotonicity of `frequency`: if `l1 ⊑ l2` (equal weights, pointwise-related generators) and both
have positive total weight (`h1, h2`), then `frequency l1 h1 ⊑ frequency l2 h2`. -/
private theorem frequency_le [Gen G] {l1 l2 : List (Nat × (Unit → G α))} (h : l1 ⊑ l2)
    (h1 : 0 < List.sum (List.map Prod.fst l1))
    (h2 : 0 < List.sum (List.map Prod.fst l2)) :
    frequency l1 h1 ⊑ frequency l2 h2 := by
  have hsum := sumOfWeights_le h
  have hchoose : (chooseNat 0 ((map Prod.fst l1).sum - 1) (Nat.zero_le _) : G Nat)
      = chooseNat 0 ((map Prod.fst l2).sum - 1) (Nat.zero_le _) := by
    congr 1
    omega
  simp only [frequency]
  rw [hchoose]
  apply MonoBind.bind_mono_right
  intro i
  by_cases hi : i < (map Prod.fst l1).sum
  . rw [dite_eq_left hi, dite_eq_left (hsum ▸ hi)]
    apply frequencyAux_le
    assumption
  . rw [dite_eq_right hi, dite_eq_right (hsum ▸ hi)]
    apply PartialOrder.rel_refl

@[partial_fixpoint_monotone]
theorem monotone_frequency [Gen G] {γ : Sort w} [PartialOrder γ]
    (gs : γ → List (Nat × (Unit → G α)))
    (hne : ∀ x, 0 < List.sum (List.map Prod.fst (gs x)))
    (hmono : monotone gs) :
    monotone (fun x => frequency (gs x) (hne x)) := by
  unfold monotone at *
  intro x y hxy
  apply frequency_le
  apply hmono
  assumption

@[partial_fixpoint_monotone]
theorem monotone_vectorOf [Gen G] {γ : Sort w} [PartialOrder γ]
    (n : Nat) (g : γ → G α) (hg : monotone g) :
    monotone (fun x => vectorOf n (g x)) := by
  unfold monotone at *
  induction n with
  | zero =>
    intro x y hxy
    simp [vectorOf]
    apply PartialOrder.rel_refl
  | succ n' IH =>
    intro x y hxy
    simp [vectorOf_succ]
    apply monotone_bind <;> try assumption
    apply monotone_of_monotone_apply
    intro z
    apply monotone_bind <;> (unfold monotone; intro x' y' hxy')
    . apply IH
      assumption
    . dsimp
      apply PartialOrder.rel_refl

@[partial_fixpoint_monotone]
theorem monotone_listOfMaxLength [Gen G] {γ : Sort w} [PartialOrder γ]
    (n : Nat) (g : γ → G α) (hg : monotone g) :
    monotone (fun x => listOfMaxLength n (g x)) := by
  unfold listOfMaxLength
  apply monotone_bind
  . apply monotone_const
  . dsimp
    apply monotone_of_monotone_apply
    intro ⟨x, hge, hle⟩
    dsimp
    apply monotone_vectorOf
    assumption

end monotonicity

/-! ## Recursive combinators

`partial_fixpoint` rebuilds each body's monotonicity proof from the `@[partial_fixpoint_monotone]`
lemmas in scope at the definition, so a combinator whose body recurses under `oneOf` has to come
after `monotone_oneOf`. -/

section recursive_combinators

/-- Generates a (possibly empty) list with unbounded length where each element is produced using
`g`.  Note: this produces the empty list 50% of the time, so for production generators, you should
consider using other combinators, e.g. `listOfMaxLength`. -/
def listOf [Gen G] (g : G α) : G (List α) := do
  oneOf [
    fun _ => pure [],
    fun _ => do
      let x ← g
      let xs ← listOf g
      return x :: xs]
partial_fixpoint

/-- Generates a *non-empty* list with unbounded length, where each element is produced using `g`. -/
def nonEmptyListOf {G α} [Gen G] (g : G α) : G (List α) := do
  oneOf [
    fun _ => do let x ← g; pure [x],
    fun _ => do
      let x ← g
      let xs ← nonEmptyListOf g
      return x :: xs]
partial_fixpoint

@[partial_fixpoint_monotone]
theorem monotone_listOf [Gen G] {γ : Sort w} [PartialOrder γ]
    (g : γ → G α) (hg : monotone g) :
    monotone (fun x => listOf (g x)) := by
  unfold monotone
  intro x y hxy
  show listOf (g x) ⊑ listOf (g y)
  generalize hw : listOf (g y) = w
  delta listOf
  apply Lean.Order.fix_induct (motive := fun z => z ⊑ w)
  · intro c hc hall
    apply Lean.Order.csup_le <;> assumption
  · intro z hz
    subst hw
    unfold listOf
    apply oneOf_le
    refine ⟨rfl, ?_⟩
    rintro (_ | _ | i) h1 h2 <;> intro _
    · apply PartialOrder.rel_refl
    · apply PartialOrder.rel_trans (MonoBind.bind_mono_left (hg x y hxy))
      apply MonoBind.bind_mono_right
      intro a
      apply MonoBind.bind_mono_left
      assumption
    · simp at h1
      omega

@[partial_fixpoint_monotone]
theorem monotone_nonEmptyListOf [Gen G] {γ : Sort w} [PartialOrder γ]
    (g : γ → G α) (hg : monotone g) :
    monotone (fun x => nonEmptyListOf (g x)) := by
  unfold monotone
  intro x y hxy
  show nonEmptyListOf (g x) ⊑ nonEmptyListOf (g y)
  generalize hw : nonEmptyListOf (g y) = w
  delta nonEmptyListOf
  apply Lean.Order.fix_induct (motive := fun z => z ⊑ w)
  · intro c hc hall
    apply Lean.Order.csup_le <;> assumption
  · intro z hz
    subst hw
    unfold nonEmptyListOf
    apply oneOf_le
    refine ⟨rfl, ?_⟩
    rintro (_ | _ | i) h1 h2 <;> intro _
    · unfold monotone at hg
      apply MonoBind.bind_mono_left
      apply hg
      assumption
    · apply PartialOrder.rel_trans (MonoBind.bind_mono_left (hg x y hxy))
      apply MonoBind.bind_mono_right
      intro a
      apply MonoBind.bind_mono_left
      assumption
    · simp at h1
      omega

end recursive_combinators
