import Basalt.Examples.BST
import Basalt.Examples.ArbNat
import Basalt.Examples.ArbList
import Basalt.Examples.ArbChar
import Basalt.Examples.ArbString
import Basalt.Examples.SortedList
import Basalt.Examples.Monoid
import Basalt.Examples.AllTwoList
import Basalt.Examples.AllTwoTree
import Basalt.Examples.Heap
